/**
 * Regenerate src/client/pages.ts from the files under src/client/pages/.
 * Bun 1.3 has no import.meta.glob, so the registry is explicit imports;
 * this script keeps it in sync. Run: bun run pages
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = "src/client/pages";

function walk(dir: string): string[] {
	return readdirSync(dir).flatMap((name) => {
		const p = join(dir, name);
		return statSync(p).isDirectory() ? walk(p) : p.endsWith(".svelte") ? [p] : [];
	});
}

const files = walk(ROOT)
	.map((p) => relative(ROOT, p))
	.sort();
const ident = (f: string) => `P_${f.replace(/\.svelte$/, "").replace(/[^A-Za-z0-9]/g, "_")}`;

const out = `/**
 * Page registry — GENERATED by scripts/gen-pages.ts (bun run pages).
 * Explicit imports work identically in the Bun server runtime and the
 * Bun.build client bundle. Keys use the \`./pages/<Name>.svelte\` convention
 * that \`resolve()\` builds from the Inertia component name.
 */
import type { Component } from "svelte";
${files.map((f) => `import ${ident(f)} from "./pages/${f}";`).join("\n")}

// biome-ignore lint/suspicious/noExplicitAny: pages take heterogeneous props
type PageModule = { default: Component<any> };

export const pages: Record<string, PageModule> = {
${files.map((f) => `\t"./pages/${f}": { default: ${ident(f)} },`).join("\n")}
};

/** Fallback for unknown component names — never resolve to undefined. */
export const notFoundPage: PageModule = { default: P_NotFound };
`;
writeFileSync("src/client/pages.ts", out);
console.log(`pages.ts: ${files.length} pages`);
