/**
 * Page registry — GENERATED by scripts/gen-pages.ts (bun run pages).
 * Explicit imports work identically in the Bun server runtime and the
 * Bun.build client bundle. Keys use the `./pages/<Name>.svelte` convention
 * that `resolve()` builds from the Inertia component name.
 */
import type { Component } from "svelte";
import P_ForgotPassword from "./pages/ForgotPassword.svelte";
import P_Home from "./pages/Home.svelte";
import P_Login from "./pages/Login.svelte";
import P_NotFound from "./pages/NotFound.svelte";
import P_Profile from "./pages/Profile.svelte";
import P_Register from "./pages/Register.svelte";
import P_ResetPassword from "./pages/ResetPassword.svelte";
import P_activity_Index from "./pages/activity/Index.svelte";
import P_adminland_Index from "./pages/adminland/Index.svelte";
import P_calendar_Index from "./pages/calendar/Index.svelte";
import P_cards_Index from "./pages/cards/Index.svelte";
import P_cards_Show from "./pages/cards/Show.svelte";
import P_chat_Index from "./pages/chat/Index.svelte";
import P_checkins_Answer from "./pages/checkins/Answer.svelte";
import P_checkins_Form from "./pages/checkins/Form.svelte";
import P_checkins_Index from "./pages/checkins/Index.svelte";
import P_checkins_Show from "./pages/checkins/Show.svelte";
import P_docs_Form from "./pages/docs/Form.svelte";
import P_docs_Index from "./pages/docs/Index.svelte";
import P_docs_Show from "./pages/docs/Show.svelte";
import P_everything_Index from "./pages/everything/Index.svelte";
import P_home_Index from "./pages/home/Index.svelte";
import P_messages_Form from "./pages/messages/Form.svelte";
import P_messages_Index from "./pages/messages/Index.svelte";
import P_messages_Show from "./pages/messages/Show.svelte";
import P_people_Show from "./pages/people/Show.svelte";
import P_pings_Index from "./pages/pings/Index.svelte";
import P_pings_Show from "./pages/pings/Show.svelte";
import P_projects_Edit from "./pages/projects/Edit.svelte";
import P_projects_Integrations from "./pages/projects/Integrations.svelte";
import P_projects_New from "./pages/projects/New.svelte";
import P_projects_People from "./pages/projects/People.svelte";
import P_projects_Show from "./pages/projects/Show.svelte";
import P_reports_Index from "./pages/reports/Index.svelte";
import P_schedule_Form from "./pages/schedule/Form.svelte";
import P_schedule_Index from "./pages/schedule/Index.svelte";
import P_schedule_Show from "./pages/schedule/Show.svelte";
import P_search_Index from "./pages/search/Index.svelte";
import P_timesheet_Index from "./pages/timesheet/Index.svelte";
import P_todos_Index from "./pages/todos/Index.svelte";
import P_todos_List from "./pages/todos/List.svelte";
import P_todos_Show from "./pages/todos/Show.svelte";
import P_workspaces_Index from "./pages/workspaces/Index.svelte";

// biome-ignore lint/suspicious/noExplicitAny: pages take heterogeneous props
type PageModule = { default: Component<any> };

export const pages: Record<string, PageModule> = {
	"./pages/ForgotPassword.svelte": { default: P_ForgotPassword },
	"./pages/Home.svelte": { default: P_Home },
	"./pages/Login.svelte": { default: P_Login },
	"./pages/NotFound.svelte": { default: P_NotFound },
	"./pages/Profile.svelte": { default: P_Profile },
	"./pages/Register.svelte": { default: P_Register },
	"./pages/ResetPassword.svelte": { default: P_ResetPassword },
	"./pages/activity/Index.svelte": { default: P_activity_Index },
	"./pages/adminland/Index.svelte": { default: P_adminland_Index },
	"./pages/calendar/Index.svelte": { default: P_calendar_Index },
	"./pages/cards/Index.svelte": { default: P_cards_Index },
	"./pages/cards/Show.svelte": { default: P_cards_Show },
	"./pages/chat/Index.svelte": { default: P_chat_Index },
	"./pages/checkins/Answer.svelte": { default: P_checkins_Answer },
	"./pages/checkins/Form.svelte": { default: P_checkins_Form },
	"./pages/checkins/Index.svelte": { default: P_checkins_Index },
	"./pages/checkins/Show.svelte": { default: P_checkins_Show },
	"./pages/docs/Form.svelte": { default: P_docs_Form },
	"./pages/docs/Index.svelte": { default: P_docs_Index },
	"./pages/docs/Show.svelte": { default: P_docs_Show },
	"./pages/everything/Index.svelte": { default: P_everything_Index },
	"./pages/home/Index.svelte": { default: P_home_Index },
	"./pages/messages/Form.svelte": { default: P_messages_Form },
	"./pages/messages/Index.svelte": { default: P_messages_Index },
	"./pages/messages/Show.svelte": { default: P_messages_Show },
	"./pages/people/Show.svelte": { default: P_people_Show },
	"./pages/pings/Index.svelte": { default: P_pings_Index },
	"./pages/pings/Show.svelte": { default: P_pings_Show },
	"./pages/projects/Edit.svelte": { default: P_projects_Edit },
	"./pages/projects/Integrations.svelte": { default: P_projects_Integrations },
	"./pages/projects/New.svelte": { default: P_projects_New },
	"./pages/projects/People.svelte": { default: P_projects_People },
	"./pages/projects/Show.svelte": { default: P_projects_Show },
	"./pages/reports/Index.svelte": { default: P_reports_Index },
	"./pages/schedule/Form.svelte": { default: P_schedule_Form },
	"./pages/schedule/Index.svelte": { default: P_schedule_Index },
	"./pages/schedule/Show.svelte": { default: P_schedule_Show },
	"./pages/search/Index.svelte": { default: P_search_Index },
	"./pages/timesheet/Index.svelte": { default: P_timesheet_Index },
	"./pages/todos/Index.svelte": { default: P_todos_Index },
	"./pages/todos/List.svelte": { default: P_todos_List },
	"./pages/todos/Show.svelte": { default: P_todos_Show },
	"./pages/workspaces/Index.svelte": { default: P_workspaces_Index },
};

/** Fallback for unknown component names — never resolve to undefined. */
export const notFoundPage: PageModule = { default: P_NotFound };
